config/routes.rb
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  # GET /about
  get "about", to: "about#index"
     # change  route url but don't change file name
  # get "about-us", to: "about#index", as: :about

  # TODO's routes
  get "todo", to: "todo#index"
  get "new_todo", to: "todo#new"
  get "edit_todo", to: "todo#edit"

  # change password(update)
  get "password", to:"passwords#edit", as: :edit_password
  patch"password", to:"passwords#update"

  # forget password
  get "password/reset", to:"password_resets#new"
  post"password/reset", to:"password_resets#create"
   # this use for mailer 
  get "password/reset/edit", to:"password_resets#edit"
  patch"password/reset/edit", to:"password_resets#update"



  # sign up routes
  get "sign_up", to:"registrations#new"
  post "sign_up", to:"registrations#create"

  # sign in routes
  get "sign_in", to:"sessions#new"
  post "sign_in", to:"sessions#create"

  # logout routes
  delete "logout", to:"sessions#destroy"

  # root route 
  # these are all three type can we define root route
    # Defines the root path route ("/")
  # get "/", to:"main#index"
  # get "", to:"main#index"
    # root "articles#index"
  root to:"main#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/user.rb
# email:string
# password_digest:string

# password:string virtual
# passwor_confirmation:string virtual
class User < ApplicationRecord
    has_secure_password

    validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message:"Must be a valid email address" }
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user
     
    def set_current_user
        if session[:user_id]
            Current.user = User.find_by(id: session[:user_id])
        end
    end

    def require_user_logged_in!
        redirect_to sign_in_path, alert: "You must be sign in to do that." if Current.user.nil? 
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
       # flash.now[:notice] = "logged sucessfully"
       # flash.now[:alert] = "Invalid Email OR Password"
    end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController

    def new
    end

    def create
        @user = User.find_by(email: params[:email])

        if @user.present?
            #send email for password reset
            PasswordMailer.with(user: @user).reset.deliver_now
        end
        redirect_to  root_path,  notice:"if  an accunt with that email was found , we send link to reset your password" 
    end

    def edit
        @user = User.find_signed!(params[:token], purpose: "password_reset" )
    rescue ActiveSupport::MessageVerifier::InvalidSignature
        redirect_to sign_in_path , alert: "Your token has expired, please try again "
    end

    def update
        @user = User.find_signed!(params[:token], purpose: "password_reset" )
        if @user.update(password_params)
            redirect_to sign_in_path, notice:"Your password was reset sucessfully. please sign in "
        else
            render :edit
        end
    end

    private
    def password_params
        params.require(:user).permit(:password, :password_confirmation)
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
    before_action :require_user_logged_in!
    
    def edit
    end

    def update
        if Current.user.update(password_params)
          redirect_to root_path, notice: "Password updated" 
        else
            render :edit
        end
    end

    private
    def password_params
        params.require(:user).permit(:password, :password_confirmation)
    end


end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController

    def new
        @user = User.new
    end

    def create
       @user = User.new(user_params)
       if @user.save
        session[:user_id] = @user.id
        redirect_to root_path, notice: "Sucessfully created account"
       else
        render :new
       end
    end

    private
    def user_params
        params.require(:user).permit(:email, :password, :password_confirmation)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
   # create login form 
    def new
    end 
    
    def create
        user = User.find_by(email: params[:email])
        if user.present? && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to root_path, notice: "logged in successfully"
        else
            flash[:alert] = "Invalid email or password"
            render :new
        end
    end
   # log out 
    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: "Logged out" 
    end 
end

app/controllers/todo_controller.rb
class TodoController < ApplicationController
    def index
    end

    def new
    end 

    def edit
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<h1>hello world </h1>
<h2>Today is <%= today = Time.now.strftime("%A,%d%B%Y") %></h2>
<h3> this is about page</h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todoapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%# getbootstrap's css source link %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%# getbootstrap's JavaScript plugin and dependency %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
   <%= render partial: "shared/navbar"%>
   <div class="container">
   <%= render partial: "shared/flash"%>
      <%= yield %>
   </div>
  </body>
</html>

app/views/main/index.html.erb
<div class="d-flex align-items-center justify-content-center">
     <h1> hello world</h1>
</div>

<div class="d-flex align-items-center justify-content-center">
     <h3>this is home page</h3>
</div>

app/views/password_resets/edit.html.erb
<h1>Reset your password ?</h1>

  <%= form_with model: @user, url: password_reset_edit_path(token: params[:token]) do |form| %>
     <% if form.object.errors.any? %>
       <div class="alert alert-danger">
        <% form.object.errors.full_messages.each do |message|%>
           <div><%= message %></div>
        <% end %>
       </div>
     <% end %>
         
        <div class="mb-3">
            <%= form.label :Password %>
            <%= form.password_field :password, class:"form-control", placeholder:"password" %>
        </div>

        <div class="mb-3">
            <%= form.label :Password_Confirmation %>
            <%= form.password_field :password_confirmation, class:"form-control", placeholder:"password" %>
        </div>


        <div class="mb-3">
           <%= form.submit "Reset Password ", class:"btn btn-primary" %>
        </div>
<% end %>

app/views/password_resets/new.html.erb
<h1>Forgot your password ?</h1>

<%= form_with url: password_reset_path  do |form| %>
     
     <div class="mb-3">
           <%= form.label :Email %>
           <%= form.text_field :email, class:"form-control", placeholder:"Email" %>
    </div>

        <div class="mb-3">
           <%= form.submit "Reset Password ", class:"btn btn-primary" %>
        </div>
<% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
<div class="alert alert-success mt-4"  role="alert" >
    <%= flash[:notice] %>
</div>
<% end %>

<% if flash[:alert] %>
<div class="alert alert-danger mt-4" role="alert">
   <%= flash[:alert] %>
</div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
   <% if Current.user %>
     <%= link_to"Todo", todo_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to"Home", root_path, class:"nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class:"nav-link active" %>
        </li>
      </ul>

    <% else %>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to"Home", root_path, class:"nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class:"nav-link active" %>
        </li>
        <% end %>
        </li>
      </ul>
      <%# in side the nav bar but diffrent side %>
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if Current.user %>
        <li class="nav-item">
         <%# <span>logged in as:-<%= Current.user.email %> <%# </span> %>
         <%= link_to Current.user.email, edit_password_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
            <%# call the delete mathod and destroy the session and log out %>
           <%= button_to "Logout", logout_path, method: :delete, class:" nav-link btn btn-danger" %>
        </li>
        <% else %>
        <li class="nav-item">
           <%= link_to "sign up", sign_up_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
           <%= link_to "log in", sign_in_path, class:"nav-link" %>
        </li>
        <% end %>
      </ul>

    </div>
  </div>
</nav>

app/views/todo/edit.html.erb
<h1>Edit Todo</h1>

<div data-turbo="false">
    <%= form_with url: edit_todo_path do |form|%>
      
        <div class="mb-3">
           <%= form.label :todo %>
           <%= form.text_field :todo, class:"form-control", placeholder:"todo" %>
        </div>

        <div class="mb-3">
          <%= form.label :due_date%>
          <div class="form-control">
             <%= form.datetime_select  :due_date%>
          </div>
        </div>

        <div class="mb-3">
           <%= form.submit "update todo", class:"btn btn-primary" %>
           <%# change submit to delet %>
          <%= form.submit "delete todo", class:"btn btn-danger" %>
        </div>
     <% end %>
</div>

app/views/todo/index.html.erb
<%#<div id="friends" %>  
<h3>To day:-<%= today = Time.now.strftime("%A,%d%B%Y,%H:%M") %></h3>

<h1>Todo list</h1>
<div class="table-responsive" >
<table class ="table table-striped table-bordered"  >
    <thead class="table-dark">
    <tr>
        <th>TODO</th>
        <th>DUE</th>
        <th colspan ="1" > </th>
    </tr>
    </thead>
    <tbody>
      <tr>
        <td> test</td>
        <td> date time</td>

           <td><%= link_to "EDIT ", edit_todo_path, class:"btn btn-danger btn-sm" %></td>
      </tr>
    </tbody>
</table>
</div>

<%= link_to "New todo", new_todo_path, class:"btn btn-dark"  %>
<%# = link_to "Edit todo", edit_todo_path, class:"btn btn-danger"  %>

app/views/todo/new.html.erb
<h1>New Todo</h1>

<div data-turbo="false">
    <%= form_with url: new_todo_path do |form|%>
      
        <div class="mb-3">
           <%= form.label :todo %>
           <%= form.text_field :todo, class:"form-control", placeholder:"todo" %>
        </div>

        <div class="mb-3">
          <%= form.label :due_date%>
          <div class="form-control">
             <%= form.datetime_select  :due_date%>
          </div>
        </div>

        <div class="mb-3">
           <%= form.submit "New todo", class:"btn btn-primary" %>
        </div>
     <% end %>
</div>